apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: komposed-sh
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Komposed.sh CRD showcase
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - '*'
