# permissions for end users to view komposemanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: komposed-sh
    app.kubernetes.io/managed-by: kustomize
  name: komposemanifest-viewer-role
rules:
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests/status
  verbs:
  - get
