# permissions for end users to edit komposemanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: komposed-sh
    app.kubernetes.io/managed-by: kustomize
  name: komposemanifest-editor-role
rules:
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests/status
  verbs:
  - get
