---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests/finalizers
  verbs:
  - update
- apiGroups:
  - komposed-sh.komposed.sh
  resources:
  - komposemanifests/status
  verbs:
  - get
  - patch
  - update
