apiVersion: komposed-sh.komposed.sh/v1alpha1
kind: KomposeManifest
metadata:
  labels:
    app.kubernetes.io/name: komposed-sh
    app.kubernetes.io/managed-by: kustomize
  name: cobalt-sample
spec:
  dockerCompose: |
    services:
        cobalt:
            image: ghcr.io/imputnet/cobalt:11
            init: true
            read_only: true
            restart: unless-stopped
            container_name: cobalt
            ports:
                - 9000:9000/tcp
            environment:
                API_URL: "https://api.url.example/"
            labels:
                - com.centurylinklabs.watchtower.scope=cobalt
  
