name: Release Operator

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Push Operator Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push Operator image
        working-directory: operator
        run: |
          make docker-build docker-push IMG=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.VERSION }}

      - name: Generate install.yaml
        working-directory: operator
        run: |
          make build-installer IMG=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.VERSION }}

      - name: Commit and push install.yaml to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git checkout main
          cp operator/dist/install.yaml operator/dist/install.yaml
          git add operator/dist/install.yaml
          git commit -m "chore: update install.yaml for version ${{ steps.vars.outputs.VERSION }}"
          git push origin main
